Newfilestructure
Msalter91/postme pull request #1
Opened 2022-07-13 08:34 UTC by Msalter91

All post controls work in an object oriented way and all follow PSR-12. The only change I still need to make for compliance is to create a namespace for all classes but this will take some time.

2022-07-15 11:28 UTC, szreka commented
Hello

2022-07-18 13:12 UTC, cfuzek requested changes

2022-07-18 13:12 UTC, cfuzek commented on app/code/Post/Controllers/Index.php
> +
Please Remove the space

2022-07-18 13:12 UTC, cfuzek commented on app/code/User/Api/Data/UserInterface.php
> +
Please remove the space

2022-07-18 13:12 UTC, cfuzek commented on app/code/User/Api/UserRepositoryInterface.php
> +
Please remove the space

2022-07-18 13:12 UTC, cfuzek commented on app/code/User/Api/UserRepositoryInterface.php
> +
Please remove the space

2022-07-18 13:12 UTC, cfuzek commented on app/code/User/Controllers/Users.php
> +    public function createUserSession($user)
Please add the type declaration for the argument type

2022-07-18 13:12 UTC, cfuzek commented on app/code/User/Controllers/Users.php
>                      die('Something has gone wrong');
We should not use die in the code. Please review a different solution

2022-07-18 13:12 UTC, cfuzek commented on app/code/User/Controllers/Users.php
>                      //Create session
Please remove the comment

2022-07-18 13:12 UTC, cfuzek commented on app/code/User/Controllers/Users.php
>              // Load the form
Please remove the comment

2022-07-18 13:12 UTC, cfuzek commented on app/code/User/Model/User.php
> +    public function register($data): bool
You should use the argument type and $data should be an object of the class User

2022-07-18 13:12 UTC, cfuzek commented on app/code/User/Model/User.php
> +    public function login($email, $password): bool | object
Argument type missing

2022-07-18 13:12 UTC, cfuzek commented on app/code/User/Model/User.php
> +    public function getUserById($id): bool | object
Argument type missing

2022-07-18 13:12 UTC, cfuzek commented on app/code/User/Model/User.php
> +        // TODO: Implement setUserId() method.
Please complete the implementation

2022-07-18 13:12 UTC, cfuzek commented on app/code/User/Model/User.php
> +    public function findUserByEmail($email): bool
Argument type missing

2022-07-18 13:12 UTC, cfuzek commented on app/code/Post/Controllers/Index.php
> +            var_dump($_SESSION['user_id']);
Please remove the debug

2022-07-18 13:13 UTC, cfuzek commented on app/code/User/Controllers/Users.php
test

2022-07-18 15:11 UTC, Msalter91 commented on app/code/User/Model/User.php
> +    public function register($data): bool
We were only working on the posts part of the model so the user still mostly follows the old structure. I can work on the user throughout the week to bring it in line.

2022-07-19 08:27 UTC, rszekely commented on app/code/Post/Controllers/Index.php
> +        if ($_SERVER['REQUEST_METHOD'] == 'POST') {
Try an early return here, so ie:
```
 if ($_SERVER['REQUEST_METHOD'] != 'POST') {
   $this->view('posts/add', $post);
   return;
} 
```

2022-07-19 08:29 UTC, rszekely commented on app/code/Post/Controllers/Index.php
> +        if ($_SERVER['REQUEST_METHOD'] == 'POST') {
If you like it, you could try refactoring the whole class.

2022-07-20 09:21 UTC, merged